# Generated by Django 5.0 on 2023-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=200)),
                ("rating", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
            ],
        ),
    ]
